### PR TITLE
update to v2022.1

### PR DESCRIPTION
**Pull request by matthiasdiener**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by inducer** [comment]
Thanks!

**Comment by asmeurer** [comment]
I think urwid_readline needs to be added as a dependency.

**Comment by asmeurer** [comment]
Might be useful to have some way to start the debugger and immediately exit that we could use a better test in the recipe than `pudb --help`.

**Comment by inducer** [comment]
Oof, good point. Thanks for pointing that out. I missed that.

https://github.com/conda-forge/staged-recipes/pull/17486

**Comment by inducer** [comment]
https://github.com/conda-forge/pudb-feedstock/pull/21

**Pull request merged**
