### PR TITLE
Convert to noarch: python

### PR DESCRIPTION
**Pull request by wshanks**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This PR converts the package to `noarch: python`. pudb depends on urwid which has a compiled extension, but pudb itself is pure Python, so I think it can be noarch. Together with https://github.com/conda-forge/urwid-feedstock/pull/12, this PR would enable pudb to be used on ppc64le. I am not sure how to handle the build number / arch migration part.

### CODE REVIEW

**Comment by wshanks** [comment]
Hmm, I am not sure about the pypy failures. I switched the build script to use pip instead of python setup.py following the linter's suggestion which may be related. Or maybe the feedstock just needs to be re-rendered properly for noarch? I wanted to get some feedback on how to convernt to noarch first.

**Comment by scopatz** [comment]
Yeah, if you change to noarch it definitely needs to be rerendered

**Comment by wshanks** [comment]
@conda-forge-admin, please rerender

**Comment by inducer** [comment]
Would we bump the build number for this?

**Comment by scopatz** [comment]
You probably should

**Review by inducer — APPROVED** [review]
Looks fine to me, but I don't know much about noarch pacakges.

**Comment by wshanks** [comment]
So do we wait to see what @asmeurer thinks?

**Comment by scopatz** [comment]
@inducer - you are a maintainer, so if you are comfortable with it, you can merge

**Comment by inducer** [comment]
OK, great. @willsALMANJ, thanks for working on this.

**Pull request merged**
