### PR TITLE
pudb 2024.1.3

### PR DESCRIPTION
**Pull request by jeongseok-meta**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeongseok-meta** [comment]
It has been a while since I last updated this recipe, which was on 2022.1.3 (two years ago!). I hope this pull request gets merged soon!

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by inducer** [comment]
Thanks! @jeongseok-meta, want to help maintain this recipe?

**Comment by jeongseok-meta** [comment]
Yes, I'd be happy to help with maintaining this feedstock!

**Comment by jeongseok-meta** [comment]
@inducer thank you for the offer! I've created https://github.com/conda-forge/pudb-feedstock/pull/25 for adding myself as maintainer

**Pull request merged**
